function citationaleatoire(){
	var citation = ["Abraham Lincoln - Si j'avais deux visages, vous croyez que je porterais vraiment celui-ci ?",
"Alan Corenk - La d&eacute;mocratie, c'est choisir des dictateurs apr&egrave;s qu'ils nous ont dit ce que nous pensions vouloir entendre. ",
"Aldous Huxley - Tant que les gens admireront les dictateurs, les C&eacute;sar et les Napol&eacute;on ressurgiront et les rendront malheureux.",
"Ambrose Bierce - R&eacute;volution. En politique, changement brutal de mauvais gouvernement.",
"Anastasio Somoza - Vous avez gagn&eacute; les &eacute;lections, mais j'ai gagn&eacute; le d&eacute;compte des voix.",
"Anatole France - Si 50 millions de personnes disent une b&ecirc;tise, c'est quand m&ecirc;me une b&ecirc;tise.",
"Andr&eacute; Malraux - On ne fait pas de politique avec de la morale, mais on n'en fait pas davantage sans.",
"Anonyme - Les politiciens sont comme les couches. On en change pour les m&ecirc;mes raisons.",
"Anonyme - N'attribuez jamais &agrave; la m&eacute;chancet&eacute; ce qui s'explique tout simplement par la b&ecirc;tise.",
"Anonyme - Ne votez pas, &ccedil;a ne fait que les encourager.",
"Aristote - Toute nation a le gouvernement qu'elle m&eacute;rite.",
"Art Spander - Ce qu'il y a de bien avec la d&eacute;mocratie, c'est que tous les votants ont une chance de faire quelque chose de stupide.",
"Arthur Mutambara - Il vaut mieux poss&eacute;der 10% d'un &eacute;l&eacute;phant que 100% d'un rat.",
"Arthur Schopenhauer - Chaque nation tourne les autres en ridicule et elles ont toutes raison.",
"Augusto Pinochet - Aucune feuille d'arbre ne bouge si je ne la fais pas bouger moi-m&ecirc;me. Je veux que ce soit bien clair !",
"Augusto Pinochet - J'ai une mine patibulaire. C'est peut-&ecirc;tre pour &ccedil;a qu'on dit que je suis un dictateur.",
"Augusto Pinochet - Je les regarde d'en haut car Dieu m'y a plac&eacute;.",
"Augusto Pinochet - Je mourrai. Mon successeur mourra aussi. Mais vous n'aurez pas d'&eacute;lections.",
"Augusto Pinochet - Je ne suis pas du genre &agrave; faire des menaces. Je donne un seul avertissement, et le jour o&ugrave; on touche &agrave; un de mes hommes, la loi ne compte plus.",
"Benito Mussolini - Les hommes en ont assez de la libert&eacute;.",
"Benito Mussolini - Tout dans l'Etat, rien en dehors de l'Etat, rien contre l’Etat.",
"Benjamin Disraeli - La strat&eacute;gie la plus dangereuse consiste &agrave; enjamber un pr&eacute;cipice en deux sauts.",
"Benjamin Disraeli - Quelqu'un m'est sympathique s'il est d'accord avec moi.",
"Bob Edwards - J'ai compris ce qu'&eacute;tait vraiment un homme d'Etat, c'est un homme politique mort. Il nous faut plus d'hommes d'Etat.",
"Charles Bukowski - La diff&eacute;rence entre une d&eacute;mocratie et une dictature, c'est qu'en d&eacute;mocratie on vote d'abord et on re&ccedil;oit des ordres apr&egrave;s, alors qu'en dictature on ne perd pas son temps &agrave; voter.",
"Charles Caleb Colton - La corruption est comme une boule de neige. Une fois lanc&eacute;e, on ne l'arr&ecirc;te plus.",
"Charles Taylor - Nous n'expulsons pas les journalistes mais ils sont libres de partir d&egrave;s qu'ils le veulent.",
"Charles de Gaulle - Je suis arriv&eacute; &agrave; la conclusion que la politique est une affaire trop s&eacute;rieuse pour &ecirc;tre laiss&eacute;e aux politiciens.",
"Charlie Chaplin - Je reste avant tout un clown. Cela me place beaucoup plus haut qu'aucun politicien.",
"Charlie Chaplin - Un meurtre fait un assassin, un million de morts font un h&eacute;ros. Le chiffre sanctifie.",
"Che Guevara - En quoi est-ce un ''profit mutuel'' que de vendre sur le march&eacute; mondial des mati&egrave;res premi&egrave;res qui co&ucirc;tent beaucoup trop de sueur et de souffrance aux pays en d&eacute;veloppement ?",
"Che Guevara - Je ne suis ni le Christ ni un philanthrope. Je suis tout le contraire du Christ...",
"Che Guevara - Je ne suis pas un lib&eacute;rateur. Les lib&eacute;rateurs n'existent pas. Le peuple se lib&egrave;re lui-m&ecirc;me.",
"Che Guevara - Je sais que vous &ecirc;tes l&agrave; pour me tuer. Tirez, lâche, ce n'est qu'un homme que vous allez tuer.",
"Che Guevara - La d&eacute;mocratie n'est pas compatible avec l'oligarchie financi&egrave;re.",
"Che Guevara - La r&eacute;volution n'est pas une pomme qui tombe de l'arbre quand elle est m&ucirc;re. Il faut la faire tomber.",
"Che Guevara - Lors d'une r&eacute;volution, si c'en est une vraie, on gagne ou on meurt.",
"Che Guevara - Pour faire fusiller des hommes, les preuves ne sont pas n&eacute;cessaires. Ce sont des d&eacute;tails bourgeois et archa&iuml;ques.",
"Che Guevara - Si nous voulons assurer la paix mondiale, la c&oelig;xistence pacifique ne doit pas &ecirc;tre exclusive aux pays puissants.",
"Chester Bowles - Gouverner est une chose trop importante pour qu'on la laisse aux hommes politiques.",
"Cullen Hightower - Nous avons bien du mal &agrave; imaginer nos vies plus dures et plus frustrantes. Le Congr&egrave;s, lui, n'a aucun mal &agrave; cela.",
"Dalton Camp - La politique est surtout faite d'impr&eacute;cisions.",
"Dan Quayle - L'avenir sera meilleur demain.",
"David M. Ogilvy - Les publicit&eacute;s pour les politiques devraient &ecirc;tre interdites. Ce sont les plus malhonn&ecirc;tes de toutes.",
"David Wolf - L'id&eacute;alisme, c'est ce qui pr&eacute;c&egrave;de l'exp&eacute;rience ; le cynisme, c'est ce qui la suit.",
"Donald H. Rumsfeld - Si personne ne vous critique, c'est que vous ne faites pas grand-chose.",
"Dorothy Parker - Occupez-vous du superflu, le n&eacute;cessaire s'occupera de lui-m&ecirc;me.",
"Dwight Eisenhower - Celui qui veut &ecirc;tre pr&eacute;sident est soit un &eacute;gocentrique, soit un fou.",
"E. B. White - La d&eacute;mocratie repose sur le pari que plus de la moiti&eacute; de la population a raison plus de la moiti&eacute; du temps.",
"Edith Sitwell - Les gens sont pr&ecirc;ts &agrave; croire n'importe quoi, tant que ce n'est pas fond&eacute; sur la v&eacute;rit&eacute;.",
"Edmund Burke - Les tyrans ont rarement besoin de pr&eacute;textes.",
"Emiliano Zapata - La terre et la libert&eacute; !",
"Erich Honecker - Ni un b&oelig;uf ni un âne ne peuvent arr&ecirc;ter le progr&egrave;s du socialisme. ",
"Ernest Benn - La politique est l'art de chercher des probl&egrave;mes, de d&eacute;couvrir s'il y en a ou non, de trouver une mauvaise explication et de parvenir &agrave; mal les traiter.",
"Eugene McCarthy - Il est dangereux pour un candidat &agrave; la pr&eacute;sidence de faire des promesses dont les candidats risquent de se souvenir.",
"Evita Peron - L&agrave; o&ugrave; il y a un ouvrier, il y a une nation.",
"Evita Peron - On n'accomplit rien sans fanatisme.",
"Evita Peron - R&eacute;pondons &agrave; la violence par la violence. Si l'un de nous tombe aujourd'hui, cinq d'entre eux doivent tomber demain.",
"Ferdinand Marcos - A quoi sert la d&eacute;mocratie si elle ne sert pas les pauvres ?",
"Fidel Castro - ... Si M. Kennedy n'aime pas le socialisme, qu'il sache que nous n'aimons ni l'imp&eacute;rialisme, ni le capitalisme.",
"Fidel Castro - Ce pays est un paradis, dans le sens spirituel du mot. Et je dis que nous pr&eacute;f&eacute;rons mourir au paradis plut&ocirc;t que de survivre en enfer.",
"Fidel Castro - Dans les r&eacute;volutions, il n'y a pas de place pour les &eacute;lections. Il n'y a pas gouvernement plus d&eacute;mocratique en Am&eacute;rique latine que le gouvernement r&eacute;volutionnaire.",
"Fidel Castro - Ils parlent d'&eacute;chec du socialisme, mais en quoi le capitalisme a-t-il &eacute;t&eacute; un succ&egrave;s en Afrique, en Asie et en Am&eacute;rique du sud ?",
"Fidel Castro - La r&eacute;volution n'est pas un lit de roses. La r&eacute;volution, c'est une lutte entre l'avenir et le pass&eacute;.",
"Fidel Castro - Les id&eacute;es n'ont pas besoin d'arme.",
"Fidel Castro - Les universit&eacute;s ne sont ouvertes qu'&agrave; ceux qui partagent mes vues r&eacute;volutionnaires.",
"Fidel Castro - Peu importe que vous me condamniez : l'histoire me pardonnera.",
"Fidel Castro - Si survivre aux attentats &eacute;tait une discipline olympique, je gagnerais la m&eacute;daille d'or.",
"Frank Bainimarama - Je n'ai aucune raison d'&ecirc;tre bon avec des gens qui blessent la nation...",
"Frank Dane - Avec tous les idiots de son c&ocirc;t&eacute;, on peut gagner n'importe quelle &eacute;lection.",
"Frank Hubbard - On aimerait voter pour le meilleur mais il ne fait jamais partie des candidats.",
"Frank Lloyd Wright - La v&eacute;rit&eacute; est plus importante que les faits.",
"Frank Zappa - La politique est la partie divertissante de l'industrie.",
"Franklin D. Roosevelt - En politique, rien n'arrive par hasard. Chaque fois qu'un &eacute;v&eacute;nement survient, on peut &ecirc;tre certain qu'il avait &eacute;t&eacute; pr&eacute;vu pour se d&eacute;rouler ainsi.",
"Franklin D. Roosevelt - La libert&eacute; ne se donne pas, on la prend.",
"Franklin P. Adams - On gagne une &eacute;lection non parce que les gens ont vot&eacute; pour vous, mais parce qu'ils ont vot&eacute; contre les autres.",
"Franz Kafka - Chaque r&eacute;volution s'&eacute;vapore en ne laissant derri&egrave;re elle que le d&eacute;p&ocirc;t d'une nouvelle bureaucratie.",
"Fran&ccedil;ois Duvalier - Je connais le peuple ha&iuml;tien car je suis le peuple ha&iuml;tien.",
"G. K. Chesterton - Tout homme politique est, au sens fort du terme, un homme politique qui promet",
"George F. Will - L'id&eacute;alisme est une bonne chose. Mais quand il approche de la r&eacute;alit&eacute;, les co&ucirc;ts deviennent prohibitifs.",
"George Orwell - Le lib&eacute;ral, un admirateur de pouvoir sans pouvoir.",
"George Orwell - On n'&eacute;tablit pas une dictature pour sauvegarder une r&eacute;volution. On fait une r&eacute;volution pour &eacute;tablir une dictature.",
"George W. Bush - Une dictature, ce serait beaucoup plus simple, pas de doute sur la question.",
"Gore Vidal - Deux mots composent ''Politique''. ''Poli'' veut dire ''plusieurs'' en grec, et ''tique'' est un parasite suceur de sang.",
"Groucho Marx - Ce sont mes principes, et si vous ne les aimez pas... Ce n'est pas grave, j'en ai d'autres.",
"G&eacute;n&eacute;ral William Sherman - Si je suis nomin&eacute;, je refuserai. Si je suis &eacute;lu, je n'exercerai pas mon mandat.",
"Haile Selassie I - Nous avons fini le boulot. Que devons-nous faire des outils ?",
"Harry S. Truman - Quand votre voisin perd son travail, c'est la r&eacute;cession. Quand vous perdez le v&ocirc;tre, c'est la d&eacute;pression.",
"Harry S. Truman - Quand vous avez un gouvernement efficace, vous avez une dictature.",
"Henry A. Kissinger - 90% des hommes politiques entachent la r&eacute;putation des 10% restants.",
"Henry Cate, VII - Le probl&egrave;me avec les plaisanteries politiques, c'est qu'elles finissent par &ecirc;tre &eacute;lues.",
"Henry David Thoreau - Le t&eacute;moignage par induction est parfois tr&egrave;s convaincant, surtout lorsqu'on trouve une truite dans du lait.",
"Henry Kissinger - Il ne peut pas y avoir de crise la semaine prochaine. Mon emploi du temps est d&eacute;j&agrave; rempli.",
"Henry Kissinger - Je ne vois pas pourquoi nous devrions rester sans rien faire et voir un pays devenir communiste &agrave; cause de l'irresponsabilit&eacute; de son peuple.",
"Henry Kissinger - Les probl&egrave;mes sont beaucoup trop importants pour que les &eacute;lecteurs chiliens d&eacute;cident seuls.",
"Henry Kissinger - M&ecirc;me un parano&iuml;aque peut avoir des ennemis.",
"Herbert Hoover - Quand on pense qu'on peut enfin r&eacute;soudre un probl&egrave;me, le probl&egrave;me a chang&eacute;.",
"Hugo Chavez - Avant-hier, je pensais que j'allais devoir d&eacute;cr&eacute;ter l'&eacute;tat d'urgence, mais aujourd'hui je pense que &ccedil;a devrait aller.",
"Hugo Chavez - Certains jeux vous apprennent &agrave; tuer. Une fois, on m'a montr&eacute; un jeu dont le but &eacute;tait de trouver Chavez et de le tuer.",
"Hugo Chavez - Je l'ai d&eacute;j&agrave; dit mais je suis convaincu que le meilleur moyen de construire un monde meilleur n'est pas le capitalisme. Le capitalisme nous conduit droit en enfer.",
"Hugo Chavez - Dans toute nation, certains doivent mourir. Ce sont ces sacrifices qui permettent de faire respecter la loi et l'ordre.",
"Hugo Chavez - La politique, c'est comme la boxe, vous essayez d'assommer vos adversaires.",
"Hugo Chavez - Parfois, les gens prennent ce que je dis pour ce que je pense. ",
"Hugo Chavez - Personne ne court plus vite qu'une balle.",
"Imelda Marcos - Non, je n'ai jamais eu 3000 paires de chaussures. Juste 1060.",
"Imelda Marcos - Qu'on gagne ou qu'on perde, nous allons faire les boutiques apr&egrave;s les &eacute;lections.",
"Indira Gandhi - On ne peut pas se serrer la main quand le poing est ferm&eacute;.",
"J. Edgar Hoover - La justice va de paire avec la loi et l'ordre.",
"J. Edgar Hoover - Nous ne sommes qu'une organisation qui rassemble des renseignements. Nous ne condamnons personne. Nous ne blanchissons personne.",
"Jay Leno - Si les hommes politiques disaient la v&eacute;rit&eacute;, nous serions au ch&ocirc;mage.",
"Jean-Bertrand Aristide - La communaut&eacute; internationale veut que nous acceptions une proposition qui signifierait la fin de l'opposition.",
"Jean-Bertrand Aristide - Trente-deux coups d'Etat, c'est assez.",
"John Adams - La peur est la fondation de chaque gouvernement.",
"John Adams - Le bonheur d'une soci&eacute;t&eacute; marque la fin du gouvernement.",
"John Adams - L&agrave; o&ugrave; se terminent les &eacute;lections, commence l'esclavage.",
"John F. Kennedy - Ceux qui emp&ecirc;chent les r&eacute;volutions pacifiques provoqueront les r&eacute;volutions violentes.",
"John F. Kennedy - L'humanit&eacute; doit mettre fin &agrave; la guerre ou la guerre mettra fin &agrave; l'humanit&eacute;.",
"John Kennedy - Ne demande pas ce que ton pays peut faire pour toi, demande ce que tu peux faire pour ton pays.",
"John Kenneth Galbraith - Avec le capitalisme, l'homme exploite l'homme. Avec le communisme, c'est l'inverse.",
"John Kenneth Galbraith - Si tout le reste &eacute;choue, l'immortalit&eacute; reste la plus spectaculaire des erreurs.",
"John Lehman - Le pouvoir corrompt. Mais le pouvoir absolu, c'est pas mal.",
"John Stuart Mill - Ce qu'il y a de particuli&egrave;rement n&eacute;faste &agrave; imposer le silence &agrave; l'expression d'une opinion, c'est que cela revient &agrave; voler l'humanit&eacute;.",
"Joseph McCarthy - Je vois rouge !",
"Joseph Staline - Je me moque de savoir qui votera dans le parti et comment. Par contre, il est tr&egrave;s important de savoir qui comptera les votes et comment.",
"Joseph Staline - Les id&eacute;es ont plus de pouvoir que les fusils. Nous ne voulons pas que nos ennemis aient des fusils, alors pourquoi les laisserions-nous avoir des id&eacute;es ?",
"Josip Broz Tito - Staline, arr&ecirc;te de m'envoyer des tueurs. Nous en avons d&eacute;j&agrave; captur&eacute; cinq... Si tu n'arr&ecirc;tes pas, j'enverrai moi aussi un tueur &agrave; Moscou, et il suffira.",
"Jules C&eacute;sar - Si vous devez enfreindre la loi, faites-le pour obtenir le pouvoir. Sinon, respectez-la.",
"Karl Marx - La d&eacute;mocratie est le chemin du socialisme.",
"Kim Il Sung - L&eacute;nine a v&eacute;cu, L&eacute;nine vit, L&eacute;nine vivra.",
"Lenny Bruce - Le communisme est comme une grosse soci&eacute;t&eacute; de t&eacute;l&eacute;coms.",
"Leo Rosten - L'argent ne permet pas d'acheter le bonheur, mais la pauvret&eacute; non plus.",
"Leonid Brejnev - Le probl&egrave;me avec les &eacute;lections libres, c'est qu'on ne sait pas qui va gagner.",
"Lester Pearson - La politique, c'est savoir utiliser des objets contondants.",
"Lord Acton - Le pouvoir tend &agrave; corrompre, et le pouvoir absolu corrompt absolument.",
"Lord Acton - Le probl&egrave;me, ce n'est pas qu'une classe sociale en particulier ne m&eacute;rite pas de gouverner. Aucune d'entre elle ne le m&eacute;rite.",
"L&eacute;on Trotsky - L'insurrection est un art. Elle a ses lois et ses r&egrave;gles.",
"L&eacute;on Trotsky - Le moyen ne peut &ecirc;tre justifi&eacute; que par la fin. Mais la fin a aussi besoin de justification.",
"L&eacute;on Trotsky - Ne pas croire en la force, c'est comme ne pas croire en la gravit&eacute;.",
"Malcolm X - On ne peut dissocier la paix de la libert&eacute; car personne n'est en paix s'il n'est pas libre.",
"Mao Tse-Toung - Toutes les guerres contre-r&eacute;volutionnaires sont injustes, toutes les guerres r&eacute;volutionnaires sont justes.",
"Mao Ts&eacute;-Toung - Il est dangereux de lire trop de livres.",
"Mao Ts&eacute;-Toung - Il y a une s&eacute;rieuse tendance au capitalisme parmi les paysans &agrave; l'aise.",
"Mao Ts&eacute;-Toung - Le communisme n'a aucun rapport avec l'amour. Le communisme est le marteau avec lequel nous fracasserons l'ennemi.",
"Mao Ts&eacute;-Toung - Notre syst&egrave;me est une dictature d&eacute;mocratique populaire, dirig&eacute;e par la classe ouvri&egrave;re et bas&eacute;e sur l'alliance des paysans et du prol&eacute;tariat.",
"Margaret Thatcher - Etre puissant, c'est comme &ecirc;tre une femme. Si vous devez le pr&eacute;ciser, c'est que vous ne l'&ecirc;tes pas.",
"Mark B. Cohen - Rien ne peut plus ali&eacute;ner un &eacute;lecteur d'un syst&egrave;me politique que de voter pour le candidat qui va gagner.",
"Martin Luther King - Encore et encore, nous devons atteindre ce niveau exalt&eacute; o&ugrave; nous opposons &agrave; la force physique, la force de l'âme.",
"Milton Friedman - La solution d'un gouvernement &agrave; un probl&egrave;me est souvent pire que le probl&egrave;me.",
"Milton Friedman - Les gouvernements ne retiennent jamais rien. Seules les peuples se souviennent.",
"Mobutu Sese Seko - Le chef est le chef, l'aigle qui vole si haut que la bave du crapaud ne l'atteint pas.",
"Mobutu Sese Seko- Quand on veut voler, on vole peu mais bien. Si l'on vole pour devenir riche en un jour, on se fait prendre.",
"Mobutu Sese Seko - Si je pouvais tout recommencer, je serais fermier.",
"Mogens Jallberg - En d&eacute;mocratie, c'est votre vote qui compte. En f&eacute;odalit&eacute;, c'est votre comte qui vote.",
"Mohammed Reza Pahlavi - Laissez-moi vous dire sans fard qu'&ecirc;tre roi ne m'a apport&eacute; que des maux de t&ecirc;te.",
"Muammar Khadafi - Th&eacute;oriquement, c'est de la d&eacute;mocratie. Dans les faits, c'est la loi du plus fort.",
"Napol&eacute;on Bonaparte - En politique l'absurdit&eacute; n'est pas un handicap.",
"Napol&eacute;on Bonaparte - L'histoire est une suite de mensonges sur lesquels on est d'accord.",
"Napol&eacute;on Bonaparte - Un chef est un marchand d'espoir.",
"Nelson Mandela - Dans mon pays, on va en prison et apr&egrave;s on devient pr&eacute;sident.",
"Nelson Mandela - Rien n'arr&ecirc;tera notre marche pour la libert&eacute;. Nous ne laisserons pas la peur s'interposer.",
"Nguyen Cao Ky - Je n'ai jamais foment&eacute; de coup d'Etat. Ils m'ont forc&eacute; &agrave; devenir Premier ministre car ils pensaient que c'&eacute;tait le seul moyen de me faire passer sur la chaise &eacute;lectrique.",
"Nicolas Gomez Davila - L'Histoire a prouv&eacute; que gouverner un pays est une trop grande tâche pour un homme.",
"Nicolas Gomez Davila - Les r&eacute;volutions font peur, mais les campagnes &eacute;lectorales font vomir.",
"Nicolas Machiavel - La politique n'a rien &agrave; voir avec la morale.",
"Nikita Khroutchev - Appelez &ccedil;a comme vous voulez, mais ce sont les primes qui poussent les gens &agrave; travailler plus.",
"Nikita Khroutchev - Les politiciens sont tous les m&ecirc;mes : ils promettent de construire un pont, m&ecirc;me l&agrave; o&ugrave; il n'y a pas de rivi&egrave;re.",
"Oscar Wilde - Il faut toujours pardonner &agrave; ses ennemis, &ccedil;a les emb&ecirc;te terriblement. ",
"Oscar Wilde - La d&eacute;mocratie, c'est le matraquage du peuple, par le peuple et pour le peuple. ",
"Oscar Wilde - Le secret de la vie est de savoir appr&eacute;cier le plaisir d'&ecirc;tre terriblement d&eacute;tromp&eacute;.",
"P. J. O'Rourke - Dans la vie, il est n&eacute;cessaire d'avoir un peu de gouvernement et un peu de chance, mais il faut &ecirc;tre fou pour leur faire confiance.",
"Paul Watson - Peu importe ce qui est vrai, ce qui compte, c'est ce que les gens croient vrai.",
"Peter de Vries - Tout le monde me d&eacute;teste parce que tout le monde m'aime.",
"Platon - On mesure un homme &agrave; ce qu'il fait du pouvoir.",
"Platon - Refuser de participer &agrave; la vie politique, cela revient &agrave; se laisser gouverner par des gens inf&eacute;rieurs &agrave; soi.",
"Pol Pot - Je suis modeste. Je ne veux pas dire aux gens que je suis un leader. ",
"Pol Pot - Le seul bon bourgeois est un bourgeois mort.",
"Rafael Trujillo - Pr&eacute;sident dans deux si&egrave;cles.",
"Ralph Nader - Int&eacute;ressez-vous &agrave; la politique avant qu'elle ne s'int&eacute;resse plus &agrave; vous.",
"Richard Nixon - Le r&ecirc;ve am&eacute;ricain ne vient pas &agrave; ceux qui s'endorment.",
"Richard Nixon - Les gens ont le droit de savoir si leur pr&eacute;sident est un escroc. Je ne le suis pas. J'ai gagn&eacute; tout ce que j'ai.",
"Richard Nixon - Un pays qui d&eacute;cr&egrave;te qu'il faut installer la paix par des moyens pacifiques est un pays qui est sur le point de se faire absorber par un autre.",
"Robert Mugabe - Il est peut-&ecirc;tre n&eacute;cessaire d'utiliser des m&eacute;thodes non constitutionnelles.",
"Robert Mugabe - Je veux que tout le monde joue au cricket au Zimbabwe. Je veux que notre pays soit une nation de gentlemen.",
"Robert Orben - N'avez-vous jamais l'impression qu'on ne vote que pour v&eacute;rifier si les sondages ont raison ?  ",
"Ronald Reagan - Je suis un &eacute;cologiste. Je suis pour un air pur.",
"Ronald Reagan - Le gouvernement voit l'&eacute;conomie de la mani&egrave;re suivante : si elle avance, taxez-la. Si elle continue &agrave; avancer, r&eacute;gulez-la. Si elle arr&ecirc;te d'avancer, subventionnez-la.",
"Saddam Hussein - La politique consiste &agrave; dire qu'on va faire une chose alors qu'on a l'intention d'en faire une autre. Finalement, on ne fait ni l'une ni l'autre.",
"Saparmurat Niyazov - Laissez la vie des Turkm&egrave;nes &ecirc;tre aussi belle que nos melons.",
"Saparmurat Niyazov - Personnellement, je ne veux pas voir ma photo ou des statues &agrave; mon effigie dans les rues... Mais c'est ce que veut le peuple.",
"Silvio Berlusconi - Je suis le J&eacute;sus Christ de la politique. Je suis une victime patiente, je me sacrifie pour tous.",
"Silvio Berlusconi - La presse &eacute;trang&egrave;re est g&eacute;n&eacute;ralement de gauche et ne nous d&eacute;crit pas comme nous sommes vraiment.",
"Silvio Berlusconi - Par d&eacute;finition, &eacute;tant Premier ministre, je ne peux pas &ecirc;tre un menteur.",
"Simon Cameron - Un homme politique honn&ecirc;te est un homme politique qui, une fois qu'il est vendu, reste tout le temps vendu ensuite.",
"Sir Winston Churchill - J'ai toujours pens&eacute; qu'un homme politique devait &ecirc;tre jug&eacute; par l'animosit&eacute; qu'il inspire &agrave; ses adversaires.",
"Soren Kierkegaard - Le peuple r&eacute;clame la libert&eacute; de parole pour compenser la libert&eacute; de penser qu'ils n'utilisent jamais.",
"Sun Tzu - Un chef conduit par l'exemple, pas par la force.",
"Thomas Jefferson - L’esprit de r&eacute;sistance au gouvernement est si pr&eacute;cieux en certaines occasions, que j’esp&egrave;re qu’il sera toujours gard&eacute; en vie.",
"Thomas Jefferson - Tout ce dont la tyrannie a besoin pour prendre pied, c'est que les hommes de bonne conscience restent silencieux.",
"Todor Zhivkov - Cette ann&eacute;e, une usine de semi-conducteurs. L'ann&eacute;e prochaine, une usine de conducteurs complets !",
"Todor Zhivkov - La police appartient au peuple et le peuple appartient &agrave; la police.",
"Todor Zhivkov - Nous devons prendre un virage radical, &agrave; 360 degr&eacute;s.",
"Todor Zhivkov - Un bon journaliste n'&eacute;crit pas ce que les gens disent, il &eacute;crit ce qu'il est cens&eacute; &eacute;crire.",
"Tom Robbins - Quand on ne croit plus &agrave; la magie, on finit par croire au gouvernement et &agrave; l'&eacute;conomie.",
"Victor Hugo - Il y a toujours plus de mis&egrave;re chez les plus pauvres que d'humanit&eacute; chez les plus riches.",
"Victor Hugo - Quand la dictature est un fait, la r&eacute;volution est un droit.",
"Viktor Yanoukovitch - Nous avons pour but de gagner les &eacute;lections.",
"Viktor Yanoukovitch - Nous devons am&eacute;liorer nos vies et nous le ferons ensemble. Tous les citoyens et moi, en tant que pr&eacute;sident.",
"Viktor Youshchenko - Le r&eacute;gime a peur du peuple parce qu'il sait que des &eacute;lections libres signeront son arr&ecirc;t de mort.",
"Viktor Youshchenko - Mon c&oelig;ur, comme le v&ocirc;tre, se brise quand il voit comment le gouvernement vole les richesses du pays et vend nos int&eacute;r&ecirc;ts nationaux.",
"Vladimir L&eacute;nine - Il est vrai que la libert&eacute; est pr&eacute;cieuse ; si pr&eacute;cieuse qu'elle doit &ecirc;tre rationn&eacute;e.",
"Vladimir L&eacute;nine - Un homme avec un fusil peut diriger 100 hommes d&eacute;sarm&eacute;s.",
"Vladimir Poutine - Quiconque regrette l'Union Sovi&eacute;tique n'a pas de c&oelig;ur. Quiconque souhaite son retour n'a pas de cervelle.",
"Vladimir Poutine - Un ancien membre du KGB, &ccedil;a n'existe pas.",
"Vladimir Poutine - Vous devez ob&eacute;ir aux lois, toujours, pas seulement quand elle vous prend par les parties.",
"Vladimir Zhirinovsky - Nous devons forcer le gouvernement &agrave; mettre fin &agrave; la migration des oiseaux. Nous devons utiliser toutes nos troupes pour abattre les oiseaux...",
"Vladimir Zhirinovsky - Si la Russie s'&eacute;l&egrave;ve, cela signifie que les Etats-Unis sombrent.",
"Voltaire - Il est interdit de tuer, donc tous les meurtriers doivent &ecirc;tre punis, sauf s'ils tuent en grand nombre et au son des trompettes.",
"Voltaire - Il est interdit de tuer, les meurtriers ne sont donc r&eacute;compens&eacute;s que s'ils agissent en grand nombre et au son des clairons.",
"Voltaire - La forme de gouvernement id&eacute;ale est la d&eacute;mocratie r&eacute;gul&eacute;e par des assassinats.",
"Voltaire - Les habiles tyrans ne sont jamais punis.",
"Will Rogers - Ce qui est bien avec ces candidats, c'est qu'un seul d'entre eux peut gagner.",
"Will Rogers - Le communisme est comme la prohibition. C'est une bonne id&eacute;e, mais &ccedil;a ne marchera jamais.",
"William Gaddis - Le pouvoir ne corrompt pas les gens, ce sont les gens qui corrompent le pouvoir. ",
"Winston Churchill - La d&eacute;mocratie est le pire des syst&egrave;mes &agrave; l'exclusion de tous les autres.",
"Winston Churchill - Le meilleur argument contre la d&eacute;mocratie est une conversation de cinq minutes avec l'&eacute;lecteur moyen.",
"Winston Churchill - Le vice du capitalisme, c'est la r&eacute;partition in&eacute;galitaire des richesses. La vertu du socialisme, c'est le partage &eacute;galitaire de la pauvret&eacute;.",
"Woodrow Wilson - La r&eacute;pression s&egrave;me les graines de la r&eacute;volution.",]

document.getElementById('citation').innerHTML ="";
document.getElementById('citation').innerHTML += citation[Math.round(Math.random()*(citation.length-1))];

}